@startuml Watches_Ecommerce_Sprint2
left to right direction
actor Customer
actor Administrator

rectangle "Watches_Ecommerce" {
  usecase "Select product details (color, size, quantity)" as UC_SelectDetails
  usecase "Place an order" as UC_Order
  usecase "Receive order confirmation" as UC_OrderConfirmation
  usecase "Send order notification" as UC_SendNotification
  usecase "Manage orders" as UC_ManageOrders

  UC_SelectDetails ..> UC_Order : "«include»"
  UC_Order ..> UC_OrderConfirmation : "«include»"
  UC_OrderConfirmation ..> UC_SendNotification : "«include»"
}

Customer -- UC_SelectDetails
Customer -- UC_Order
Customer -- UC_OrderConfirmation

Administrator -- UC_ManageOrders
@enduml
